name: Test composite action
on:
  pull_request:
    paths:
      - 'action.yml'
  workflow_dispatch:    

jobs:
  test-composite-action:
    runs-on: ubuntu-latest
    steps:
    
      - name: Test action
        uses: ./
        with:
          cache: 'true'
          
      - name: Get nodes
        run: k3s kubectl get nodes -o wide

