name: Test composite action
on:
  pull_request:
    paths:
      - 'action.yml'
  workflow_dispatch:    

jobs:
  test-composite-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test action
        uses: ./
        with:
          cache: 'true'
          
      - name: Get nodes
        run: |
          export KUBECONFIG=~/.kube/config

          kubectl get nodes -o wide

